"""Renders reports/baselines.md (tables + confusion matrix PNG) from the results dict."""

from __future__ import annotations

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from . import metrics  # noqa: E402
from .paths import REPORTS_DIR  # noqa: E402


def pct(x) -> str:
    return "–" if x is None else f"{100 * x:.1f}"


def write_report(results: dict, ood_misses: list[dict], best_preds: dict, intent_sets: dict, labels: list[str]) -> None:
    sel = results["selected"]
    lines = [
        "# Baselines (P2)",
        "",
        f"Knowledge base `{results['kb_hash']}`, seed {results['seed']}. Generated by `python -m tradexcel_ml.baselines` - do not edit by hand.",
        "",
        "Everything below uses **off-the-shelf** components (at most a linear head is trained). These are the numbers the fine-tuned models in P3 must beat.",
        "",
        "**Splits.** Card questions are split 70/15/15 per card; the retriever only indexes card titles + *train* questions. "
        "Intent templates are split by template before being filled with stock names, so test sentences come from unseen templates. "
        "`test_ood` is the hand-written held-out set in deliberately different styles. Models are selected on `val` only.",
        "",
        "| split | examples | with a card target |",
        "|---|---:|---:|",
    ]
    for split, s in results["sizes"].items():
        lines.append(f"| {split} | {s['total']} | {s['card_targets']} |")

    lines += ["", "## Retrieval (which card answers the question)", "", "| retriever | val R@1 | test R@1 | test R@3 | test MRR | **OOD R@1** | OOD R@3 | OOD MRR |", "|---|---:|---:|---:|---:|---:|---:|---:|"]
    for name, r in results["retrieval"].items():
        mark = " ✅" if name == sel["retrieval"] else ""
        lines.append(
            f"| {name}{mark} | {pct(r['val']['R@1'])} | {pct(r['test']['R@1'])} | {pct(r['test']['R@3'])} | {r['test']['MRR']:.3f} "
            f"| **{pct(r['test_ood']['R@1'])}** | {pct(r['test_ood']['R@3'])} | {r['test_ood']['MRR']:.3f} |"
        )
    styles = sorted({s for r in results["retrieval"].values() for s in r["ood_R@1_by_style"]})
    lines += ["", "OOD R@1 by writing style:", "", "| retriever | " + " | ".join(styles) + " |", "|---|" + "---:|" * len(styles)]
    for name, r in results["retrieval"].items():
        lines.append(f"| {name} | " + " | ".join(pct(r["ood_R@1_by_style"].get(s)) for s in styles) + " |")

    lines += ["", "## Intent classification", "", "| model | val macro-F1 | test macro-F1 | **OOD macro-F1** | OOD acc | OOD guardrail recall | OOD out-of-scope recall |", "|---|---:|---:|---:|---:|---:|---:|"]
    for name, r in results["intent"].items():
        mark = " ✅" if name == sel["intent"] else ""
        o = r["test_ood"]
        lines.append(
            f"| {name}{mark} | {pct(r['val']['macro_f1'])} | {pct(r['test']['macro_f1'])} | **{pct(o['macro_f1'])}** | {pct(o['accuracy'])} "
            f"| {pct(o['guardrail_recall'])} | {pct(o['out_of_scope_recall'])} |"
        )
    best_ood = results["intent"][sel["intent"]]["test_ood"]["per_class_f1"]
    lines += ["", f"Per-intent OOD F1 for the selected model ({sel['intent']}):", "", "| intent | F1 |", "|---|---:|"]
    lines += [f"| {k} | {pct(v)} |" for k, v in sorted(best_ood.items(), key=lambda kv: kv[1])]
    lines += ["", "![Confusion matrix, selected intent model on test_ood](baseline_intent_confusion.png)"]

    lk, ls = results["linker"], results["linker_on_heldout_slots"]
    lines += [
        "",
        "## Stock-name linking (rule-based)",
        "",
        "| eval set | cases | exact match | precision | recall | F1 | ambiguity handled |",
        "|---|---:|---:|---:|---:|---:|---:|",
        f"| entity test set | {lk['n']} | {pct(lk['exact_match'])} | {pct(lk['precision'])} | {pct(lk['recall'])} | {pct(lk['f1'])} | {pct(lk['ambiguity_accuracy'])} |",
        f"| held-out price/holding questions | {ls['n']} | {pct(ls['exact_match'])} | {pct(ls['precision'])} | {pct(ls['recall'])} | {pct(ls['f1'])} | – |",
    ]
    if results["linker_failures"]:
        lines += ["", "Linker failures:", "", "| text | expected | got |", "|---|---|---|"]
        for f in results["linker_failures"]:
            exp = ", ".join(f["expected"]) + (f" (ambiguous: {f['expected_ambiguous']})" if f["expected_ambiguous"] else "")
            got = ", ".join(f["got"]) + (f" (ambiguous: {', '.join(f['got_ambiguous'])})" if f["got_ambiguous"] else "")
            lines.append(f"| {f['text']} | {exp or '∅'} | {got or '∅'} |")

    lines += ["", "## Encode latency (this dev machine, CPU, batch of 1)", "", "| model | p50 ms | p95 ms |", "|---|---:|---:|"]
    lines += [f"| {k} | {v['p50']:.1f} | {v['p95']:.1f} |" for k, v in results["encode_latency_ms"].items()]

    lines += ["", f"## Where the selected retriever fails (test_ood, {len(ood_misses)} misses)", "", "| query | style | expected | got |", "|---|---|---|---|"]
    lines += [f"| {m['text']} | {m['style']} | {m['expected']} | {m['got']} |" for m in ood_misses[:25]]
    if len(ood_misses) > 25:
        lines.append(f"\n…and {len(ood_misses) - 25} more in `ml/artifacts/baseline_retrieval_misses.json`.")

    lines += [
        "",
        "## Caveats",
        "",
        "- All data, including the test sets, is synthetic and written by the same author, so absolute numbers are optimistic. "
        "`test_ood` narrows that gap by using unseen phrasings and styles; real logged questions will be added as a further test set in P6.",
        "- `test_ood` is small (310 cases), so differences of a couple of points are within noise.",
        "- `test` can score *below* `test_ood`: each card's questions cover different facets of the topic, and the held-out one is often the "
        "most canonical (\"what is market cap\"), which then has to be answered from the card's other facets. `test_ood` questions target a card's main topic. "
        "(Sanity check: queries that are in the index score R@1 = 100%, so this isn't a scoring bug.)",
        "- Equal-weight RRF with BM25 can score below the dense model alone: when one retriever is much weaker, fusing ranks mostly adds its mistakes. "
        "P3 will tune the fusion weight on `val` instead.",
    ]
    (REPORTS_DIR / "baselines.md").write_text("\n".join(lines) + "\n")

    rows = intent_sets["test_ood"]
    m = metrics.confusion([e.intent for e in rows], best_preds["test_ood"], labels)
    fig, ax = plt.subplots(figsize=(9, 8))
    ax.imshow(m, cmap="Blues")
    ax.set_xticks(range(len(labels)), labels, rotation=60, ha="right")
    ax.set_yticks(range(len(labels)), labels)
    ax.set_xlabel("predicted")
    ax.set_ylabel("true")
    ax.set_title(f"Intent confusion on test_ood - {results['selected']['intent']}", fontsize=10)
    for i in range(len(labels)):
        for j in range(len(labels)):
            if m[i, j]:
                ax.text(j, i, str(m[i, j]), ha="center", va="center", fontsize=8, color="white" if m[i, j] > m.max() / 2 else "black")
    fig.tight_layout()
    fig.savefig(REPORTS_DIR / "baseline_intent_confusion.png", dpi=130)
    plt.close(fig)
