"""Renders reports/finetune.md (+ learning curve and confusion PNGs)."""

from __future__ import annotations

import json

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from . import metrics  # noqa: E402
from .paths import ARTIFACTS_DIR, REPORTS_DIR  # noqa: E402


def pct(x) -> str:
    return "–" if x is None else f"{100 * x:.1f}"


def write_p3_report(out: dict, ood_gold_intents: list[str]) -> None:
    res, sel = out["results"], out["selected"]
    lines = [
        "# Fine-tuning and the full router (P3)",
        "",
        f"Knowledge base `{out['kb_hash']}`. Generated by `python -m tradexcel_ml.evaluate` - do not edit by hand. "
        "Same splits as the [baselines](baselines.md). For every encoder, the fusion weight, intent-head regularisation and "
        "router thresholds were picked on `val` only; `test` and `test_ood` were each evaluated once.",
        "",
        "## 1. Retrieval: does fine-tuning help?",
        "",
        "R@1 = the right card is ranked first. *Fused* = weighted rank fusion with BM25, weight tuned on val.",
        "",
        "| encoder | val R@1 | test R@1 | **OOD R@1** | OOD R@3 | OOD R@1 fused | fusion weight (dense) |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for name, r in res.items():
        d = r["retrieval"]
        lines.append(
            f"| {name} | {pct(d['val']['dense']['R@1'])} | {pct(d['test']['dense']['R@1'])} | **{pct(d['test_ood']['dense']['R@1'])}** "
            f"| {pct(d['test_ood']['dense']['R@3'])} | {pct(d['test_ood']['fused']['R@1'])} | {r['fusion_weight']:.2f} |"
        )

    lines += ["", "## 2. Intent classification (logistic regression on the encoder's embeddings)", "", "| encoder | C | val macro-F1 | test macro-F1 | **OOD macro-F1** | OOD accuracy |", "|---|---:|---:|---:|---:|---:|"]
    for name, r in res.items():
        i = r["intent"]
        lines.append(f"| {name} | {r['intent_C']} | {pct(i['val']['macro_f1'])} | {pct(i['test']['macro_f1'])} | **{pct(i['test_ood']['macro_f1'])}** | {pct(i['test_ood']['accuracy'])} |")

    rq = out["rule_quality"]
    lines += [
        "",
        "## 3. The full router (what users actually get)",
        "",
        "Guard rules → classifier with a guardrail threshold → out-of-scope threshold → live-data intents (stock names must be right too) "
        "→ card retrieval with a confidence gate that asks *\"did you mean…?\"* instead of guessing.",
        "",
        "- **correct**: the right card, the right live-data intent (and stocks), or a correct fallback",
        "- **helpful**: correct, or a \"did you mean\" that includes the right card",
        "- **utility**: +1 correct, +0.5 helpful clarify, 0 useless clarify, −1 wrong (the thresholds maximise this on val, subject to catching every val guardrail)",
        "",
        "| encoder | split | correct | helpful | wrong | asks | guardrail recall | guardrail false-pos | out-of-scope recall | utility |",
        "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for name, r in res.items():
        for s in ("val", "test", "test_ood"):
            x = r["router"][s]
            bold = "**" if s == "test_ood" else ""
            lines.append(
                f"| {name if s == 'val' else ''} | {s} | {bold}{pct(x['correct'])}{bold} | {pct(x['helpful'])} | {pct(x['wrong'])} | {pct(x['clarify_rate'])} "
                f"| {bold}{pct(x['guardrail_recall'])}{bold} | {pct(x['guardrail_false_positive_rate'])} | {pct(x['oos_recall'])} | {x['utility']:.3f} |"
            )
    p = res[sel]["policy"]
    lines += [
        "",
        f"**Selected for the runtime: {sel}** (best val utility). Its thresholds: guardrail probability ≥ {p['t_guard']}, "
        f"out-of-scope below {p['t_oos']}, ask instead of answering below cosine {p['t_card']}, "
        f"{'search only the predicted intent’s cards' if p['restrict'] else 'search all non-guardrail cards'}.",
        "",
        f"Guard rules alone (written from training questions only): recall {pct(rq['val']['recall'])} / {pct(rq['test']['recall'])} / {pct(rq['test_ood']['recall'])} "
        f"on val / test / OOD guardrail questions, with {rq['val']['false_positives']} / {rq['test']['false_positives']} / {rq['test_ood']['false_positives']} false positives. "
        "The classifier threshold catches what they miss.",
        "",
        "![Router intent confusion on test_ood](finetune_router_confusion.png)",
    ]

    # learning curves
    histories = {}
    for key in ("minilm", "bge"):
        f = ARTIFACTS_DIR / "models" / key / "training_history.json"
        if f.exists():
            histories[key] = json.loads(f.read_text())
    if histories:
        lines += ["", "## 4. Training", "", "Contrastive fine-tuning, in-batch + mined hard negatives, same-card/intent pairs masked out of the negatives (see `finetune.py`).", ""]
        lines += ["| encoder | best epoch (val) | epochs run | seconds/epoch (CPU) | val R@1 before → after | val intent F1 before → after |", "|---|---:|---:|---:|---:|---:|"]
        for h in histories.values():
            hist = h["history"]
            best = next(e for e in hist if e["epoch"] == h["best_epoch"])
            secs = [e["seconds"] for e in hist if "seconds" in e]
            lines.append(
                f"| {h['label']} | {h['best_epoch']} | {len(hist) - 1} | {sum(secs) / max(1, len(secs)):.0f} "
                f"| {pct(hist[0]['val_R@1'])} → {pct(best['val_R@1'])} | {pct(hist[0]['val_intent_macro_f1'])} → {pct(best['val_intent_macro_f1'])} |"
            )
        lines += ["", "![Learning curves](finetune_learning_curves.png)"]
        fig, axes = plt.subplots(1, 3, figsize=(12, 3.4))
        for h in histories.values():
            ep = [e["epoch"] for e in h["history"]]
            axes[0].plot(ep[1:], [e["train_loss"] for e in h["history"][1:]], marker="o", label=h["label"])
            axes[1].plot(ep, [e["val_R@1"] for e in h["history"]], marker="o", label=h["label"])
            axes[2].plot(ep, [e["val_intent_macro_f1"] for e in h["history"]], marker="o", label=h["label"])
        for ax, title in zip(axes, ("train loss", "val retrieval R@1", "val intent macro-F1")):
            ax.set_title(title, fontsize=10)
            ax.set_xlabel("epoch")
            ax.grid(alpha=0.3)
        axes[0].legend(fontsize=8)
        fig.tight_layout()
        fig.savefig(REPORTS_DIR / "finetune_learning_curves.png", dpi=130)
        plt.close(fig)

    lines += ["", "## 5. Latency (this dev machine, CPU, one query)", "", "| encoder | p50 ms | p95 ms |", "|---|---:|---:|"]
    lines += [f"| {n} | {r['latency_ms']['p50']:.1f} | {r['latency_ms']['p95']:.1f} |" for n, r in res.items()]

    fails = res[sel]["ood_failures"]
    lines += ["", f"## 6. What the selected router still gets wrong on test_ood ({len(fails)} of {res[sel]['router']['test_ood']['n']})", "", "| query | style | expected | got | outcome |", "|---|---|---|---|---|"]
    lines += [f"| {f['text']} | {f['style']} | {f['expected']} | {f['got']} ({f['kind']}) | {f['outcome']} |" for f in fails]

    lines += [
        "",
        "## Caveats",
        "",
        "- Everything is synthetic and written by one author; `test_ood` narrows but doesn't close that gap. Real logged questions become a test set in P6.",
        "- Guardrail thresholds are tuned on a small val set (a handful of guardrail questions), so \"100% on val\" is a floor, not a guarantee; the rules and the runtime's fixed refusal cards are the backstop.",
        "- `test_ood` has 310 cases: a 2-3 point difference is within noise.",
    ]
    (REPORTS_DIR / "finetune.md").write_text("\n".join(lines) + "\n")

    labels = sorted(set(ood_gold_intents) | set(res[sel]["ood_router_intents"]))
    m = metrics.confusion(ood_gold_intents, res[sel]["ood_router_intents"], labels)
    fig, ax = plt.subplots(figsize=(9, 8))
    ax.imshow(m, cmap="Greens")
    ax.set_xticks(range(len(labels)), labels, rotation=60, ha="right")
    ax.set_yticks(range(len(labels)), labels)
    ax.set_xlabel("router decision")
    ax.set_ylabel("true intent")
    ax.set_title(f"Router intent decisions on test_ood - {sel}", fontsize=10)
    for i in range(len(labels)):
        for j in range(len(labels)):
            if m[i, j]:
                ax.text(j, i, str(m[i, j]), ha="center", va="center", fontsize=8, color="white" if m[i, j] > m.max() / 2 else "black")
    fig.tight_layout()
    fig.savefig(REPORTS_DIR / "finetune_router_confusion.png", dpi=130)
    plt.close(fig)
