// NSE stocks tradable on TradeXcel - the single list shared by the frontend
// (Market page, search, trade pickers) and the backend (the chat assistant's
// stock-name linking). Symbols carry Yahoo's ".NS" suffix.

export type StockListing = { symbol: string; shortName: string; fullName: string };

export const STOCK_LIST: StockListing[] = [
  { symbol: "BANKBARODA.NS", shortName: "BANKBARODA", fullName: "Bank of Baroda" },
  { symbol: "BHEL.NS", shortName: "BHEL", fullName: "Bharat Heavy Electricals Limited" },
  { symbol: "INDIGO.NS", shortName: "INDIGO", fullName: "InterGlobe Aviation (IndiGo)" },
  { symbol: "HDFCBANK.NS", shortName: "HDFC", fullName: "HDFC Bank" },
  { symbol: "TITAN.NS", shortName: "TITAN", fullName: "Titan Company" },
  { symbol: "ICICIBANK.NS", shortName: "ICICI", fullName: "ICICI Bank" },
  { symbol: "RELIANCE.NS", shortName: "RELIANCE", fullName: "Reliance Industries" },
  { symbol: "UPL.NS", shortName: "UPL", fullName: "UPL Limited" },
  { symbol: "BAJFINANCE.NS", shortName: "BAJAJ", fullName: "Bajaj Finance" },
  { symbol: "JSWENERGY.NS", shortName: "JSWENERGY", fullName: "JSW Energy" },
  { symbol: "GAIL.NS", shortName: "GAIL", fullName: "GAIL (India) Limited" },
  { symbol: "SUNPHARMA.NS", shortName: "SUNPHARMA", fullName: "Sun Pharmaceutical Industries" },
  { symbol: "TORNTPHARM.NS", shortName: "TORNTPHARM", fullName: "Torrent Pharmaceuticals" },
  { symbol: "WIPRO.NS", shortName: "WIPRO", fullName: "Wipro" },
  { symbol: "ADANIPORTS.NS", shortName: "ADANIPORTS", fullName: "Adani Ports and Special Economic Zone" },
  { symbol: "SIEMENS.NS", shortName: "SIEMENS", fullName: "Siemens Limited" },
  { symbol: "HCLTECH.NS", shortName: "HCLTECH", fullName: "HCL Technologies" },
  { symbol: "ADANIGREEN.NS", shortName: "ADANIGREEN", fullName: "Adani Green Energy" },
  { symbol: "SBIN.NS", shortName: "SBIN", fullName: "State Bank of India" },
  { symbol: "HINDALCO.NS", shortName: "HINDALCO", fullName: "Hindalco Industries" },
  { symbol: "ASIANPAINT.NS", shortName: "ASIANPAINT", fullName: "Asian Paints" },
  { symbol: "ADANIPOWER.NS", shortName: "ADANIPOWER", fullName: "Adani Power" },
  { symbol: "BEL.NS", shortName: "BEL", fullName: "Bharat Electronics Limited" },
  { symbol: "TCS.NS", shortName: "TCS", fullName: "Tata Consultancy Services" },
  { symbol: "AXISBANK.NS", shortName: "AXISBANK", fullName: "Axis Bank" },
  { symbol: "MARUTI.NS", shortName: "MARUTI", fullName: "Maruti Suzuki India" },
  { symbol: "POWERGRID.NS", shortName: "POWERGRID", fullName: "Power Grid Corporation" },
  { symbol: "PNB.NS", shortName: "PNB", fullName: "Punjab National Bank" },
  { symbol: "ITC.NS", shortName: "ITC", fullName: "ITC Ltd" },
  { symbol: "BPCL.NS", shortName: "BPCL", fullName: "Bharat Petroleum Corporation Limited" },
  { symbol: "CANBK.NS", shortName: "CANBK", fullName: "Canara Bank" },
  { symbol: "BHARTIARTL.NS", shortName: "BHARTIARTL", fullName: "Bharti Airtel" },
  { symbol: "KOTAKBANK.NS", shortName: "KOTAKBANK", fullName: "Kotak Mahindra Bank" },
  { symbol: "INDUSINDBK.NS", shortName: "INDUSINDBK", fullName: "IndusInd Bank" },
  { symbol: "FEDERALBNK.NS", shortName: "FEDERALBNK", fullName: "Federal Bank" },
  { symbol: "IDFCFIRSTB.NS", shortName: "IDFCFIRSTB", fullName: "IDFC First Bank" },
  { symbol: "BANDHANBNK.NS", shortName: "BANDHANBNK", fullName: "Bandhan Bank" },
  { symbol: "RBLBANK.NS", shortName: "RBLBANK", fullName: "RBL Bank" },
  { symbol: "AUBANK.NS", shortName: "AUBANK", fullName: "AU Small Finance Bank" },
  { symbol: "YESBANK.NS", shortName: "YESBANK", fullName: "Yes Bank" },
  { symbol: "UNIONBANK.NS", shortName: "UNIONBANK", fullName: "Union Bank of India" },
  { symbol: "BANKINDIA.NS", shortName: "BANKINDIA", fullName: "Bank of India" },
  { symbol: "INDIANB.NS", shortName: "INDIANB", fullName: "Indian Bank" },
  { symbol: "UCOBANK.NS", shortName: "UCOBANK", fullName: "UCO Bank" },
  { symbol: "MAHABANK.NS", shortName: "MAHABANK", fullName: "Bank of Maharashtra" },
  { symbol: "IOB.NS", shortName: "IOB", fullName: "Indian Overseas Bank" },
  { symbol: "SOUTHBANK.NS", shortName: "SOUTHBANK", fullName: "South Indian Bank" },
  { symbol: "KARURVYSYA.NS", shortName: "KARURVYSYA", fullName: "Karur Vysya Bank" },
  { symbol: "CUB.NS", shortName: "CUB", fullName: "City Union Bank" },
  { symbol: "DCBBANK.NS", shortName: "DCBBANK", fullName: "DCB Bank" },
  { symbol: "BAJAJFINSV.NS", shortName: "BAJAJFINSV", fullName: "Bajaj Finserv" },
  { symbol: "HDFCLIFE.NS", shortName: "HDFCLIFE", fullName: "HDFC Life Insurance Company" },
  { symbol: "SBILIFE.NS", shortName: "SBILIFE", fullName: "SBI Life Insurance Company" },
  { symbol: "ICICIPRULI.NS", shortName: "ICICIPRULI", fullName: "ICICI Prudential Life Insurance" },
  { symbol: "ICICIGI.NS", shortName: "ICICIGI", fullName: "ICICI Lombard General Insurance" },
  { symbol: "SHRIRAMFIN.NS", shortName: "SHRIRAMFIN", fullName: "Shriram Finance" },
  { symbol: "CHOLAFIN.NS", shortName: "CHOLAFIN", fullName: "Cholamandalam Investment and Finance" },
  { symbol: "MUTHOOTFIN.NS", shortName: "MUTHOOTFIN", fullName: "Muthoot Finance" },
  { symbol: "MANAPPURAM.NS", shortName: "MANAPPURAM", fullName: "Manappuram Finance" },
  { symbol: "LICHSGFIN.NS", shortName: "LICHSGFIN", fullName: "LIC Housing Finance" },
  { symbol: "PFC.NS", shortName: "PFC", fullName: "Power Finance Corporation" },
  { symbol: "RECLTD.NS", shortName: "RECLTD", fullName: "REC Limited" },
  { symbol: "IRFC.NS", shortName: "IRFC", fullName: "Indian Railway Finance Corporation" },
  { symbol: "PNBHOUSING.NS", shortName: "PNBHOUSING", fullName: "PNB Housing Finance" },
  { symbol: "SBICARD.NS", shortName: "SBICARD", fullName: "SBI Cards and Payment Services" },
  { symbol: "HDFCAMC.NS", shortName: "HDFCAMC", fullName: "HDFC Asset Management Company" },
  { symbol: "ANGELONE.NS", shortName: "ANGELONE", fullName: "Angel One" },
  { symbol: "CDSL.NS", shortName: "CDSL", fullName: "Central Depository Services" },
  { symbol: "BSE.NS", shortName: "BSE", fullName: "BSE Limited" },
  { symbol: "MCX.NS", shortName: "MCX", fullName: "Multi Commodity Exchange of India" },
  { symbol: "IEX.NS", shortName: "IEX", fullName: "Indian Energy Exchange" },
  { symbol: "CAMS.NS", shortName: "CAMS", fullName: "Computer Age Management Services" },
  { symbol: "LTF.NS", shortName: "LTF", fullName: "L&T Finance" },
  { symbol: "M&MFIN.NS", shortName: "M&MFIN", fullName: "Mahindra & Mahindra Financial Services" },
  { symbol: "IIFL.NS", shortName: "IIFL", fullName: "IIFL Finance" },
  { symbol: "INFY.NS", shortName: "INFY", fullName: "Infosys" },
  { symbol: "TECHM.NS", shortName: "TECHM", fullName: "Tech Mahindra" },
  { symbol: "MPHASIS.NS", shortName: "MPHASIS", fullName: "Mphasis" },
  { symbol: "PERSISTENT.NS", shortName: "PERSISTENT", fullName: "Persistent Systems" },
  { symbol: "COFORGE.NS", shortName: "COFORGE", fullName: "Coforge" },
  { symbol: "LTTS.NS", shortName: "LTTS", fullName: "L&T Technology Services" },
  { symbol: "OFSS.NS", shortName: "OFSS", fullName: "Oracle Financial Services Software" },
  { symbol: "KPITTECH.NS", shortName: "KPITTECH", fullName: "KPIT Technologies" },
  { symbol: "CYIENT.NS", shortName: "CYIENT", fullName: "Cyient" },
  { symbol: "TATAELXSI.NS", shortName: "TATAELXSI", fullName: "Tata Elxsi" },
  { symbol: "ZENSARTECH.NS", shortName: "ZENSARTECH", fullName: "Zensar Technologies" },
  { symbol: "NEWGEN.NS", shortName: "NEWGEN", fullName: "Newgen Software Technologies" },
  { symbol: "M&M.NS", shortName: "M&M", fullName: "Mahindra & Mahindra" },
  { symbol: "HEROMOTOCO.NS", shortName: "HEROMOTOCO", fullName: "Hero MotoCorp" },
  { symbol: "EICHERMOT.NS", shortName: "EICHERMOT", fullName: "Eicher Motors" },
  { symbol: "TVSMOTOR.NS", shortName: "TVSMOTOR", fullName: "TVS Motor Company" },
  { symbol: "ASHOKLEY.NS", shortName: "ASHOKLEY", fullName: "Ashok Leyland" },
  { symbol: "ESCORTS.NS", shortName: "ESCORTS", fullName: "Escorts Kubota" },
  { symbol: "BALKRISIND.NS", shortName: "BALKRISIND", fullName: "Balkrishna Industries" },
  { symbol: "MRF.NS", shortName: "MRF", fullName: "MRF Limited" },
  { symbol: "APOLLOTYRE.NS", shortName: "APOLLOTYRE", fullName: "Apollo Tyres" },
  { symbol: "CEATLTD.NS", shortName: "CEATLTD", fullName: "CEAT Limited" },
  { symbol: "BOSCHLTD.NS", shortName: "BOSCHLTD", fullName: "Bosch Limited" },
  { symbol: "MOTHERSON.NS", shortName: "MOTHERSON", fullName: "Samvardhana Motherson International" },
  { symbol: "BHARATFORG.NS", shortName: "BHARATFORG", fullName: "Bharat Forge" },
  { symbol: "EXIDEIND.NS", shortName: "EXIDEIND", fullName: "Exide Industries" },
  { symbol: "DRREDDY.NS", shortName: "DRREDDY", fullName: "Dr. Reddy's Laboratories" },
  { symbol: "CIPLA.NS", shortName: "CIPLA", fullName: "Cipla" },
  { symbol: "DIVISLAB.NS", shortName: "DIVISLAB", fullName: "Divi's Laboratories" },
  { symbol: "LUPIN.NS", shortName: "LUPIN", fullName: "Lupin" },
  { symbol: "AUROPHARMA.NS", shortName: "AUROPHARMA", fullName: "Aurobindo Pharma" },
  { symbol: "ALKEM.NS", shortName: "ALKEM", fullName: "Alkem Laboratories" },
  { symbol: "BIOCON.NS", shortName: "BIOCON", fullName: "Biocon" },
  { symbol: "ZYDUSLIFE.NS", shortName: "ZYDUSLIFE", fullName: "Zydus Lifesciences" },
  { symbol: "GLENMARK.NS", shortName: "GLENMARK", fullName: "Glenmark Pharmaceuticals" },
  { symbol: "IPCALAB.NS", shortName: "IPCALAB", fullName: "IPCA Laboratories" },
  { symbol: "ABBOTINDIA.NS", shortName: "ABBOTINDIA", fullName: "Abbott India" },
  { symbol: "LAURUSLABS.NS", shortName: "LAURUSLABS", fullName: "Laurus Labs" },
  { symbol: "GRANULES.NS", shortName: "GRANULES", fullName: "Granules India" },
  { symbol: "NATCOPHARM.NS", shortName: "NATCOPHARM", fullName: "Natco Pharma" },
  { symbol: "JBCHEPHARM.NS", shortName: "JBCHEPHARM", fullName: "JB Chemicals & Pharmaceuticals" },
  { symbol: "GLAND.NS", shortName: "GLAND", fullName: "Gland Pharma" },
  { symbol: "SYNGENE.NS", shortName: "SYNGENE", fullName: "Syngene International" },
  { symbol: "APOLLOHOSP.NS", shortName: "APOLLOHOSP", fullName: "Apollo Hospitals Enterprise" },
  { symbol: "FORTIS.NS", shortName: "FORTIS", fullName: "Fortis Healthcare" },
  { symbol: "MAXHEALTH.NS", shortName: "MAXHEALTH", fullName: "Max Healthcare Institute" },
  { symbol: "LALPATHLAB.NS", shortName: "LALPATHLAB", fullName: "Dr. Lal PathLabs" },
  { symbol: "METROPOLIS.NS", shortName: "METROPOLIS", fullName: "Metropolis Healthcare" },
  { symbol: "HINDUNILVR.NS", shortName: "HINDUNILVR", fullName: "Hindustan Unilever" },
  { symbol: "NESTLEIND.NS", shortName: "NESTLEIND", fullName: "Nestle India" },
  { symbol: "BRITANNIA.NS", shortName: "BRITANNIA", fullName: "Britannia Industries" },
  { symbol: "DABUR.NS", shortName: "DABUR", fullName: "Dabur India" },
  { symbol: "MARICO.NS", shortName: "MARICO", fullName: "Marico" },
  { symbol: "GODREJCP.NS", shortName: "GODREJCP", fullName: "Godrej Consumer Products" },
  { symbol: "COLPAL.NS", shortName: "COLPAL", fullName: "Colgate-Palmolive India" },
  { symbol: "TATACONSUM.NS", shortName: "TATACONSUM", fullName: "Tata Consumer Products" },
  { symbol: "UBL.NS", shortName: "UBL", fullName: "United Breweries" },
  { symbol: "VBL.NS", shortName: "VBL", fullName: "Varun Beverages" },
  { symbol: "EMAMILTD.NS", shortName: "EMAMILTD", fullName: "Emami" },
  { symbol: "PGHH.NS", shortName: "PGHH", fullName: "Procter & Gamble Hygiene and Health Care" },
  { symbol: "GILLETTE.NS", shortName: "GILLETTE", fullName: "Gillette India" },
  { symbol: "ONGC.NS", shortName: "ONGC", fullName: "Oil and Natural Gas Corporation" },
  { symbol: "IOC.NS", shortName: "IOC", fullName: "Indian Oil Corporation" },
  { symbol: "HINDPETRO.NS", shortName: "HINDPETRO", fullName: "Hindustan Petroleum Corporation" },
  { symbol: "OIL.NS", shortName: "OIL", fullName: "Oil India" },
  { symbol: "PETRONET.NS", shortName: "PETRONET", fullName: "Petronet LNG" },
  { symbol: "IGL.NS", shortName: "IGL", fullName: "Indraprastha Gas" },
  { symbol: "MGL.NS", shortName: "MGL", fullName: "Mahanagar Gas" },
  { symbol: "ATGL.NS", shortName: "ATGL", fullName: "Adani Total Gas" },
  { symbol: "NTPC.NS", shortName: "NTPC", fullName: "NTPC Limited" },
  { symbol: "TATAPOWER.NS", shortName: "TATAPOWER", fullName: "Tata Power Company" },
  { symbol: "NHPC.NS", shortName: "NHPC", fullName: "NHPC Limited" },
  { symbol: "SJVN.NS", shortName: "SJVN", fullName: "SJVN Limited" },
  { symbol: "TORNTPOWER.NS", shortName: "TORNTPOWER", fullName: "Torrent Power" },
  { symbol: "CESC.NS", shortName: "CESC", fullName: "CESC Limited" },
  { symbol: "SUZLON.NS", shortName: "SUZLON", fullName: "Suzlon Energy" },
  { symbol: "COALINDIA.NS", shortName: "COALINDIA", fullName: "Coal India" },
  { symbol: "ADANIENT.NS", shortName: "ADANIENT", fullName: "Adani Enterprises" },
  { symbol: "TATASTEEL.NS", shortName: "TATASTEEL", fullName: "Tata Steel" },
  { symbol: "JSWSTEEL.NS", shortName: "JSWSTEEL", fullName: "JSW Steel" },
  { symbol: "VEDL.NS", shortName: "VEDL", fullName: "Vedanta Limited" },
  { symbol: "JINDALSTEL.NS", shortName: "JINDALSTEL", fullName: "Jindal Steel & Power" },
  { symbol: "SAIL.NS", shortName: "SAIL", fullName: "Steel Authority of India" },
  { symbol: "NMDC.NS", shortName: "NMDC", fullName: "NMDC Limited" },
  { symbol: "NATIONALUM.NS", shortName: "NATIONALUM", fullName: "National Aluminium Company" },
  { symbol: "HINDCOPPER.NS", shortName: "HINDCOPPER", fullName: "Hindustan Copper" },
  { symbol: "MOIL.NS", shortName: "MOIL", fullName: "MOIL Limited" },
  { symbol: "APLAPOLLO.NS", shortName: "APLAPOLLO", fullName: "APL Apollo Tubes" },
  { symbol: "RATNAMANI.NS", shortName: "RATNAMANI", fullName: "Ratnamani Metals & Tubes" },
  { symbol: "ULTRACEMCO.NS", shortName: "ULTRACEMCO", fullName: "UltraTech Cement" },
  { symbol: "SHREECEM.NS", shortName: "SHREECEM", fullName: "Shree Cement" },
  { symbol: "AMBUJACEM.NS", shortName: "AMBUJACEM", fullName: "Ambuja Cements" },
  { symbol: "ACC.NS", shortName: "ACC", fullName: "ACC Limited" },
  { symbol: "DALBHARAT.NS", shortName: "DALBHARAT", fullName: "Dalmia Bharat" },
  { symbol: "JKCEMENT.NS", shortName: "JKCEMENT", fullName: "JK Cement" },
  { symbol: "RAMCOCEM.NS", shortName: "RAMCOCEM", fullName: "The Ramco Cements" },
  { symbol: "LT.NS", shortName: "LT", fullName: "Larsen & Toubro" },
  { symbol: "ABB.NS", shortName: "ABB", fullName: "ABB India" },
  { symbol: "CUMMINSIND.NS", shortName: "CUMMINSIND", fullName: "Cummins India" },
  { symbol: "HAL.NS", shortName: "HAL", fullName: "Hindustan Aeronautics" },
  { symbol: "BDL.NS", shortName: "BDL", fullName: "Bharat Dynamics" },
  { symbol: "MAZDOCK.NS", shortName: "MAZDOCK", fullName: "Mazagon Dock Shipbuilders" },
  { symbol: "COCHINSHIP.NS", shortName: "COCHINSHIP", fullName: "Cochin Shipyard" },
  { symbol: "IRCON.NS", shortName: "IRCON", fullName: "IRCON International" },
  { symbol: "RVNL.NS", shortName: "RVNL", fullName: "Rail Vikas Nigam" },
  { symbol: "CONCOR.NS", shortName: "CONCOR", fullName: "Container Corporation of India" },
  { symbol: "IRB.NS", shortName: "IRB", fullName: "IRB Infrastructure Developers" },
  { symbol: "NBCC.NS", shortName: "NBCC", fullName: "NBCC (India)" },
  { symbol: "NCC.NS", shortName: "NCC", fullName: "NCC Limited" },
  { symbol: "KEC.NS", shortName: "KEC", fullName: "KEC International" },
  { symbol: "THERMAX.NS", shortName: "THERMAX", fullName: "Thermax" },
  { symbol: "POLYCAB.NS", shortName: "POLYCAB", fullName: "Polycab India" },
  { symbol: "HAVELLS.NS", shortName: "HAVELLS", fullName: "Havells India" },
  { symbol: "VOLTAS.NS", shortName: "VOLTAS", fullName: "Voltas" },
  { symbol: "BLUESTARCO.NS", shortName: "BLUESTARCO", fullName: "Blue Star" },
  { symbol: "DIXON.NS", shortName: "DIXON", fullName: "Dixon Technologies" },
  { symbol: "AMBER.NS", shortName: "AMBER", fullName: "Amber Enterprises India" },
  { symbol: "CROMPTON.NS", shortName: "CROMPTON", fullName: "Crompton Greaves Consumer Electricals" },
  { symbol: "WHIRLPOOL.NS", shortName: "WHIRLPOOL", fullName: "Whirlpool of India" },
  { symbol: "CGPOWER.NS", shortName: "CGPOWER", fullName: "CG Power and Industrial Solutions" },
  { symbol: "KAYNES.NS", shortName: "KAYNES", fullName: "Kaynes Technology India" },
  { symbol: "ASTRAL.NS", shortName: "ASTRAL", fullName: "Astral Limited" },
  { symbol: "SUPREMEIND.NS", shortName: "SUPREMEIND", fullName: "Supreme Industries" },
  { symbol: "FINCABLES.NS", shortName: "FINCABLES", fullName: "Finolex Cables" },
  { symbol: "CENTURYPLY.NS", shortName: "CENTURYPLY", fullName: "Century Plyboards" },
  { symbol: "KEI.NS", shortName: "KEI", fullName: "KEI Industries" },
  { symbol: "IDEA.NS", shortName: "IDEA", fullName: "Vodafone Idea" },
  { symbol: "INDUSTOWER.NS", shortName: "INDUSTOWER", fullName: "Indus Towers" },
  { symbol: "TATACOMM.NS", shortName: "TATACOMM", fullName: "Tata Communications" },
  { symbol: "HFCL.NS", shortName: "HFCL", fullName: "HFCL Limited" },
  { symbol: "DMART.NS", shortName: "DMART", fullName: "Avenue Supermarts" },
  { symbol: "TRENT.NS", shortName: "TRENT", fullName: "Trent Limited" },
  { symbol: "ABFRL.NS", shortName: "ABFRL", fullName: "Aditya Birla Fashion and Retail" },
  { symbol: "PAGEIND.NS", shortName: "PAGEIND", fullName: "Page Industries" },
  { symbol: "RELAXO.NS", shortName: "RELAXO", fullName: "Relaxo Footwears" },
  { symbol: "BATAINDIA.NS", shortName: "BATAINDIA", fullName: "Bata India" },
  { symbol: "VMART.NS", shortName: "VMART", fullName: "V-Mart Retail" },
  { symbol: "SHOPERSTOP.NS", shortName: "SHOPERSTOP", fullName: "Shoppers Stop" },
  { symbol: "NYKAA.NS", shortName: "NYKAA", fullName: "FSN E-Commerce Ventures (Nykaa)" },
  { symbol: "PAYTM.NS", shortName: "PAYTM", fullName: "One97 Communications (Paytm)" },
  { symbol: "POLICYBZR.NS", shortName: "POLICYBZR", fullName: "PB Fintech (Policybazaar)" },
  { symbol: "IRCTC.NS", shortName: "IRCTC", fullName: "Indian Railway Catering and Tourism Corporation" },
  { symbol: "DELHIVERY.NS", shortName: "DELHIVERY", fullName: "Delhivery" },
  { symbol: "ZEEL.NS", shortName: "ZEEL", fullName: "Zee Entertainment Enterprises" },
  { symbol: "SUNTV.NS", shortName: "SUNTV", fullName: "Sun TV Network" },
  { symbol: "PVRINOX.NS", shortName: "PVRINOX", fullName: "PVR INOX" },
  { symbol: "NAZARA.NS", shortName: "NAZARA", fullName: "Nazara Technologies" },
  { symbol: "SAREGAMA.NS", shortName: "SAREGAMA", fullName: "Saregama India" },
  { symbol: "DLF.NS", shortName: "DLF", fullName: "DLF Limited" },
  { symbol: "GODREJPROP.NS", shortName: "GODREJPROP", fullName: "Godrej Properties" },
  { symbol: "OBEROIRLTY.NS", shortName: "OBEROIRLTY", fullName: "Oberoi Realty" },
  { symbol: "PRESTIGE.NS", shortName: "PRESTIGE", fullName: "Prestige Estates Projects" },
  { symbol: "PHOENIXLTD.NS", shortName: "PHOENIXLTD", fullName: "Phoenix Mills" },
  { symbol: "BRIGADE.NS", shortName: "BRIGADE", fullName: "Brigade Enterprises" },
  { symbol: "SOBHA.NS", shortName: "SOBHA", fullName: "Sobha Limited" },
  { symbol: "LODHA.NS", shortName: "LODHA", fullName: "Macrotech Developers (Lodha)" },
  { symbol: "PIDILITIND.NS", shortName: "PIDILITIND", fullName: "Pidilite Industries" },
  { symbol: "SRF.NS", shortName: "SRF", fullName: "SRF Limited" },
  { symbol: "AARTIIND.NS", shortName: "AARTIIND", fullName: "Aarti Industries" },
  { symbol: "DEEPAKNTR.NS", shortName: "DEEPAKNTR", fullName: "Deepak Nitrite" },
  { symbol: "NAVINFLUOR.NS", shortName: "NAVINFLUOR", fullName: "Navin Fluorine International" },
  { symbol: "TATACHEM.NS", shortName: "TATACHEM", fullName: "Tata Chemicals" },
  { symbol: "GNFC.NS", shortName: "GNFC", fullName: "Gujarat Narmada Valley Fertilizers" },
  { symbol: "CHAMBLFERT.NS", shortName: "CHAMBLFERT", fullName: "Chambal Fertilisers and Chemicals" },
  { symbol: "COROMANDEL.NS", shortName: "COROMANDEL", fullName: "Coromandel International" },
  { symbol: "PIIND.NS", shortName: "PIIND", fullName: "PI Industries" },
  { symbol: "CLEAN.NS", shortName: "CLEAN", fullName: "Clean Science and Technology" },
  { symbol: "FLUOROCHEM.NS", shortName: "FLUOROCHEM", fullName: "Gujarat Fluorochemicals" },
  { symbol: "GRASIM.NS", shortName: "GRASIM", fullName: "Grasim Industries" },
  { symbol: "GODREJIND.NS", shortName: "GODREJIND", fullName: "Godrej Industries" },
  { symbol: "BAJAJHLDNG.NS", shortName: "BAJAJHLDNG", fullName: "Bajaj Holdings & Investment" },
  { symbol: "3MINDIA.NS", shortName: "3MINDIA", fullName: "3M India" },
  { symbol: "HONAUT.NS", shortName: "HONAUT", fullName: "Honeywell Automation India" },
  { symbol: "BERGEPAINT.NS", shortName: "BERGEPAINT", fullName: "Berger Paints India" },
  { symbol: "KANSAINER.NS", shortName: "KANSAINER", fullName: "Kansai Nerolac Paints" },
  { symbol: "TRIDENT.NS", shortName: "TRIDENT", fullName: "Trident Limited" },
  { symbol: "RAYMOND.NS", shortName: "RAYMOND", fullName: "Raymond Limited" },
  { symbol: "WELCORP.NS", shortName: "WELCORP", fullName: "Welspun Corp" },
  { symbol: "BALRAMCHIN.NS", shortName: "BALRAMCHIN", fullName: "Balrampur Chini Mills" },
  { symbol: "EIDPARRY.NS", shortName: "EIDPARRY", fullName: "EID Parry (India)" },
  { symbol: "BLUEDART.NS", shortName: "BLUEDART", fullName: "Blue Dart Express" },
  { symbol: "TCI.NS", shortName: "TCI", fullName: "Transport Corporation of India" },
  { symbol: "VRLLOG.NS", shortName: "VRLLOG", fullName: "VRL Logistics" },
];
